language: python
python:
  - "3.9"

services:
  - docker
  - mysql
sudo: true
before_script: 
  - pip install docker-compose
  - bash .travis.install-mysql-5.7.sh

script:
  - docker-compose run web sh -c "python manage.py test && flake8"