version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./kyeolle:/kyeolle
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.config_secret/.env