version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./kyeolle:/kyeolle
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SECRET_KEY=supersecret
      - DEBUG=1
      - MYSQL_HOST=database.crchdrmuaucg.ap-northeast-2.rds.amazonaws.com
      - MYSQL_NAME=database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Googie)126
      - MYSQL_PORT=3306
    depends_on:
      - db
    # env_file:
    #   - ./.config_secret/.env

  db:
    image: mysql:8.0
    restart: always
    com0mand: --lower_case_table_names=1
    container_name: database-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASES=database
      - MYSQL_ROOT_PASSWORD=Googie)126
      - TZ=Asia/Seoul
    volumes:
      - /Users/Shared/data/mysql-test:/var/lib/mysql

    # command:
    #   - --character-set-server=utf8mb4
    #   - --collation-server=utf8mb4_unicode_ci

